Fixed #51 Cannot use MakeNote and noted_under in the same Actions lis…
perrygoy/screenpy pull request #52
Opened 2021-04-26 00:14 UTC by WandyYing

Fixed #51

2021-04-26 00:59 UTC, perrygoy requested changes
I think i might not be fully understanding this change. Can you explain why this approach is better?

2021-04-26 00:59 UTC, perrygoy commented on screenpy/director.py
> +        self.notebook = {}
This change actually makes this class *not* a singleton anymore. Calling `SingletonDirector()` will make new ones.

2021-04-26 02:21 UTC, WandyYing commented
Technically, Python modules ARE singletons. This approach is simple and not lazily instantianted.  FYI.  [Using module as a singleton in Python - is that ok?
](https://stackoverflow.com/questions/52929033/using-module-as-a-singleton-in-python-is-that-ok)

2021-04-26 06:42 UTC, perrygoy commented
> Technically, Python modules are singletons.

Yes, and thank you for the link, but i'm not understanding the reasoning for switching between two different ways to accomplish a singleton. Your comment on #51 said that this PR fixes the issue with `Director`—what was the issue?

2021-04-26 08:09 UTC, WandyYing commented
The request is try to fix it #51. It can make the following methods work.
```
the_actor.attempts_to(
    MakeNote.of_the(Text.of_the(EXAMPLE_FIELD)).as_("notable note"),
    Enter.the_text(noted_under("notable note")).into_the(EXAMPLE_INPUT),
)
```
I think the reason for this problem is that there is no pre instantiation. So pre instantiation might solve the problem, so I tried.

But, maybe, it doesn't have to change the way it's implemented. I might close the request if the following is possible.

```
class __Director:
    """The single Director of the screenplay.

    The Director keeps track of information for the Actors. This information
    can be retrieved using a |direction|.
    """

    notebook: dict

    _instance = None

    def __new__(cls) -> "Director":
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance.notebook = {}
        return cls._instance

    ..... 

Director = __Director()
```
I will verify this approach later.

2021-04-26 14:49 UTC, perrygoy commented
Aaah, i see.

The problem is not the pre-instantiation. What is causing #51 is that `MakeNote` hasn't yet been _performed_ when `noted_under` tries to retrieve the note. 

`noted_under` tries to retrieve the note when all the actions are being passed in to `attempts_to`, while `MakeNote` won't actually give the note to the `Director` until `MakeNote` is actually performed _inside_ of `attempts_to`. 

Does that help explain it?

2021-04-27 00:08 UTC, WandyYing commented
> `noted_under` tries to retrieve the note when all the actions are being passed in to `attempts_to`, while `MakeNote` won't actually give the note to the `Director` until `MakeNote` is actually performed _inside_ of `attempts_to`.

Yes, I agree with you. And when I checked again, I found that my test case design was wrong, which led to a false pass. I mistook the method for working. And please close the RP. lol

2021-04-27 00:08 UTC, closed without merging