63/eventually
perrygoy/screenpy pull request #72
Opened 2021-08-11 15:33 UTC by bandophahita

Adding the object Eventually

2021-08-12 02:53 UTC, perrygoy requested changes
Great work @bandophahita! I appreciate the effort you put in, this has been months in the making.

I had a few suggestions, a few changes i'd like to see, and a couple discussion points i wanted to chat through. This PR is also missing some documentation, but i'll handle writing that since i'm going to be picky about it. :P

2021-08-12 02:53 UTC, perrygoy commented on screenpy/settings.py
> +TIMEOUT = 5
I think it might be a good idea to be more specific on what this `TIMEOUT` is, unless you want both the default `Wait` behavior and the default `Eventually` behavior to use it. Even then, something more descriptive like `WAIT_TIMEOUT` might be good?

2021-08-12 02:53 UTC, perrygoy commented on screenpy/waits/eventually.py
> +    def __init__(self, performable: Performable, timeout: float = settings.TIMEOUT):
Putting `settings.TIMEOUT` here means that the default is set as the class is defined, which means it will be pretty difficult for someone to change the setting in a meaningful way. I think we'll need to have a structure like this:

```python
def __init__(self, performable: Performable, timeout: Optional[float] = None):
    if timeout is None:
        timeout = settings.TIMEOUT
    ...
```

2021-08-12 02:53 UTC, perrygoy commented on screenpy/waits/eventually.py
> +            self._poll = self.timeout
Heh, this is a good thought. I don't think i would have thought of this. :D

2021-08-12 02:53 UTC, perrygoy commented on screenpy/waits/eventually.py
> +                        self.caught_error = exc
I think this is missing an `else` clause where we re-raise the exception that should not be ignored.

I think this also could be a little bit cleaner like this:
```python
                try:
                    self.performable.perform_as(the_actor)
                    return

                except self.exceptions_to_ignore as exc:
                    self.caught_error = exc
```

One fewer line and Pylint doesn't complain!

2021-08-12 02:53 UTC, perrygoy commented on screenpy/waits/eventually.py
> +        return self
I'm not sure i understand the point of this one. Can you explain the use case?

2021-08-12 02:53 UTC, perrygoy commented on tests/test_eventually.py
> +#!/usr/bin/env python3
Going along with the suggestion above that `Eventually` should be an Action, i think these tests should be in a `TestEventually` class in the `test_actions.py` file.

2021-08-12 02:53 UTC, perrygoy commented on screenpy/waits/eventually.py
> +    class EventualPerformableBuilder:
At first, i was like "what the _h*ck_ is this." But after thinking about it and seeing how it's used in the tests, i think i really like this approach! It's really cool how it enables language.

I think it's possible that it could be a little confusing though, since there are some things that could be set before the `.waiting` call that aren't transferred over. Such as this:

```python
Eventually(SomeAction()).ignoring_exceptions(TimeoutException, TypeError).for_no_longer_than(20).seconds()
```

I think a solution could be that the `EventuallyBuilder`'s init just takes the already-initialized `Eventually` action and sets the appropriate items on it after it gets the `.seconds()` or `.milliseconds()` call:

```python
class EventuallyPerformableBuilder:
    def __init__(self, eventually: "Eventually", amount: float) -> None:
        self.eventually = eventually
        self.amount = amount
        
    def milliseconds(self) -> "Eventually":
        self.eventually.amount = self.amount / 1000
        return self.eventually
    ...
```

2021-08-12 02:53 UTC, perrygoy commented on screenpy/waits/eventually.py
> +    class EventualPerformableBuilder:
Oh, also, if someone did something like...

```
Eventually(SomeAction()).waiting(20)
```
... that might be a problem.

We can easily fix that using the above comment's fix, too, though—just have a `perform_as` in here that has the Actor perform the stored `Eventually` instance!

2021-08-12 02:53 UTC, perrygoy commented on tests/conftest.py
> +def mocked_narrator() -> Generator[mock.MagicMock, Any, None]:
👍 thanks for this!

2021-08-12 02:53 UTC, perrygoy commented on tests/test_eventually.py
> +        assert True
Any tests that need an Actor to perform the Action should go in the `test_integrations__actions.py` file, please!

2021-08-17 20:03 UTC, MarcelWilson commented on screenpy/settings.py
> +TIMEOUT = 5
I agree.. but I didn't want to assume that name without talking to you.  Should we include that to be used by `Wait` as well?  I thought that might be confusing to have a global variable and not have it used in a very obvious location.

2021-08-18 00:04 UTC, perrygoy commented on screenpy/settings.py
> +TIMEOUT = 5
Hm... yeah, i think both `Wait` and `Eventually` should have the same timeout. How about `DEFAULT_TIMEOUT`?

2021-08-18 17:38 UTC, bandophahita commented on tests/test_eventually.py
> +        assert True
These are moved

2021-08-18 17:39 UTC, bandophahita commented on tests/conftest.py
> +def mocked_narrator() -> Generator[mock.MagicMock, Any, None]:
I started a branch with a few more like this scattered about.

2021-08-18 18:10 UTC, MarcelWilson commented on tests/test_eventually.py
> +#!/usr/bin/env python3
Good call.  I move the basic `Eventually` tests to that module.

2021-08-18 18:19 UTC, MarcelWilson commented on screenpy/waits/eventually.py
> +        return self
This was a port; I didn't write the initial class so take some of this as me inferring intent:

Normally the loop will raise TimeoutError if the loop never finishes.  I'm guessing that if you wanted to raise a specific exception other than TimeoutError, this is how you would do that.   I'm not sure _why_ you'd want to do that.  I'd have to think about a potential real-world use case.

2021-08-18 18:23 UTC, MarcelWilson commented on screenpy/waits/eventually.py
> +                        self.caught_error = exc
Oh.. that's so much better.  
This was clearly ported.  Python: 1, Java: 0

2021-08-18 18:50 UTC, MarcelWilson commented on screenpy/waits/eventually.py
> +                        self.caught_error = exc
I noted that as well when porting this.

The loop catches **all** exceptions (which pylint really hates) but then check to see if we should actually raise it later.  The problem with that (as you elude with the 'missing `else`' there is a potential for the loop to timeout but never raise an exception because the one exception raised was being ignored.   In other words; we raise the exceptions we care about, we don't raise the ones being ignored.  

Should `Eventually` be more strict about this?  
Is there ever a case where timing out of the loop doesn't warrant a `TimeoutError`?

Personally I don't know if it makes sense to reach the timeout and do nothing.

2021-08-18 18:51 UTC, MarcelWilson commented on screenpy/waits/__init__.py
> +organization structure from the serenity BDD screenplay.
Agreed.

2021-08-18 19:00 UTC, MarcelWilson commented on screenpy/settings.py
> +TIMEOUT = 5
I would be more in favor of WAIT_TIMEOUT.  The variables are found in the settings file which implies a sense of "default" inherently.

Does this imply there are other forms of timeout?

2021-08-18 19:15 UTC, bandophahita commented on screenpy/waits/eventually.py
> +    class EventualPerformableBuilder:
I think you're right about not everything transferring to the new instance of `Eventually` depending on how it's called.   466bfea takes care of that part.

I'm still not sure what to do about the case of calling `waiting(1)` without the additional method call for seconds or milliseconds. I keep wondering if there is a way to make the default behavior of `waiting` to call `seconds()`

```
Eventually(SomeAction()).waiting(20)
# would be the equivalent to
Eventually(SomeAction()).waiting(20).seconds()
```

2021-08-18 19:33 UTC, bandophahita commented on screenpy/waits/eventually.py
> +    def __init__(self, performable: Performable, timeout: float = settings.TIMEOUT):
You are so right.  This is one of those lessons I continue to forget.

2021-08-18 19:37 UTC, bandophahita commented on screenpy/waits/eventually.py
> +#!/usr/bin/env python3
I didn't even think about that - I have it in my generic python file template.  Removed it.

2021-08-18 20:30 UTC, bandophahita commented on screenpy/waits/eventually.py
> +    class EventualPerformableBuilder:
> We can easily fix that using the above comment's fix, too, though—just have a perform_as in here that has the Actor perform the stored Eventually instance!
ooo... that's an interesting solution.  Let me try that.

2021-08-18 21:30 UTC, bandophahita commented on screenpy/actions/eventually.py
> +POLL_FREQUENCY = 0.5  # How long to sleep inbetween calls to the method
@perrygoy should this go into the settings file?  Feels a bit much but still...

2021-08-19 02:45 UTC, perrygoy commented on screenpy/settings.py
> +TIMEOUT = 5
The reason i didn't originally go for `WAIT_TIMEOUT` is because i'm not sure i'm imagining `Eventually` as just another wait. Like, yes, it is a way to wait for a condition to be satisfied, but it feels different somehow.

I think `WAIT_TIMEOUT` is fine, and i'm actually coming around on `TIMEOUT` on its own.

2021-08-19 02:54 UTC, perrygoy commented on screenpy/actions/eventually.py
> +POLL_FREQUENCY = 0.5  # How long to sleep inbetween calls to the method
I think we could probably move it into the `Eventually` class, with a `polling_every` -> builder -> `seconds()`?

2021-08-23 19:48 UTC, perrygoy commented on tests/conftest.py
> +            func(*args, **kwargs)
Oh yes, good call—i think that's right.

2021-08-23 19:52 UTC, perrygoy commented on screenpy/actions/eventually.py
> +                raise sigint from self.caught_error
Aw, i liked the idea at least. Yeah, let's simplify this then.

2021-08-23 20:10 UTC, perrygoy approved these changes
🎉

2021-08-23 20:10 UTC, merged

2021-08-23 20:34 UTC, bandophahita commented
You could say, we got there eventually.....
</dad_joke>